# Generated by Django 4.2.1 on 2023-06-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='apellido',
        ),
    ]
