# Generated by Django 4.2.1 on 2023-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_remove_atencion_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='numero_atencion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
