# Generated by Django 4.2.1 on 2023-06-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_atencion_numero_atencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='numero_atencion',
            new_name='numero',
        ),
    ]
