# Generated by Django 4.2.1 on 2023-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_atencion_estadoatencion_atencion_motivorechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='estadoAtencion',
            field=models.IntegerField(choices=[[0, 'Aceptada'], [1, 'Rechazada']]),
        ),
    ]
