# Generated by Django 4.2.1 on 2023-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_alter_atencion_estadoatencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='estadoAtencion',
            field=models.IntegerField(choices=[[0, 'Aceptada'], [1, 'Rechazada']], null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='motivoRechazo',
            field=models.TextField(null=True),
        ),
    ]
