# Generated by Django 4.2.1 on 2023-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_alter_atencion_estadoatencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='estadoAtencion',
        ),
        migrations.AddField(
            model_name='atencion',
            name='Aceptada',
            field=models.IntegerField(choices=[[0, 'Aceptada'], [1, '--------']], null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='Rechazada',
            field=models.IntegerField(choices=[[0, 'Rechazada'], [1, '--------']], null=True),
        ),
    ]
